tuner:
    settings:
        max_trials: 40
        directory: 'data'
        project_name: 'reuters_tuning'
        overwrite: True
        early_stopping_patience: 2
    search:
        epochs: 10
        validation_split: 0.2

training:
    num_words: 10000
    learning_rate: 0.01
    batch_size: 1024
    epochs: 10000
    validation_split: 0.2
    callbacks:
      early_stopping:
        patience: 5
